### ISSUE TITLE
Incorporating schedule tab much like homework central

### ISSUE THREAD

**Issue by mrElnekave** [saumyasinghal747/campus-central#12]
The schedule tab should be below the messages and bring you to a monthly schedule, like Schoology showing assignments, and is toggleable to show today's schedule as well, this should be like hc, however when you click on a class since its synced to Schoology all of today's and next classes assignments should be shown for that day.
Check possible direction
https://docs.google.com/drawings/d/1PiuzDUTQY58AwO0lzEikPdqHX6Klv57tugQ9RIRvowk/edit?usp=sharing

**Comment by saumyasinghal747** [comment]
I've embedded HC into a schedule tab for now, but will work on native integration soon. [See here.](https://campuscentral.repl.co/app/schedule)
